# Generated by Django 4.2.6 on 2023-12-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=100)),
                ('sal', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Deptno', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=100, unique=True)),
                ('Loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.IntegerField()),
                ('Losal', models.IntegerField()),
                ('Hisal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empno', models.IntegerField(unique=True)),
                ('Ename', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=100)),
                ('MGR', models.IntegerField()),
                ('Hiredate', models.DateField()),
                ('Salary', models.IntegerField()),
                ('Comm', models.IntegerField(null=True)),
                ('Deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
