# Generated by Django 4.2.6 on 2023-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_emp_id_alter_emp_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='Deptno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
